### ISSUE TITLE
if ( ! exists(execPath)) is failing for me

### ISSUE THREAD

**Issue by gbbauto** [Qard/node-isolated-bcrypt#2]
The detection of the proper binary is failed for me, when I am using this module in a web app, as a npm package dependency (installed in node_modules folder)

If I comment this line out, everything works, both encrypt and decrypt.

arch=x64 and platform=linux decodes to the bcrypt-linux-amd64 binary.

I will try to debug my 'fs' path when I have time, but hopefully there is something obvious.

**Comment by Qard** [comment]
Try replacing the line assigning execPath with `var execPath = join(__dirname, 'bcrypt-' + platform + '-' + arch)` and adding `var join = require('path').join` to the requires at the top. Don't have time to get onto a Linux machine at the moment, but I can have a closer look tonight, if that doesn't work.

**Comment by gbbauto** [comment]
yes, that worked, thanks
